<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [4]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
# Python lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [5]:
# Numpy Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [6]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [7]:
py_real_names[0]

'Natasha Romanoff'

In [8]:
py_super_names[0]

'Black Widow'

In [9]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [10]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

In [11]:
np_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [15]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [16]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [18]:
print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape)

10
10
(10, 2)


## 2.2 Arrays are fussy about type

Array elements must be of a single data type


In [19]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [20]:
py_list

[1, 1.5, 'A']

In [21]:
np_array # elements are converted to strings

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [22]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [23]:
np_array + 10

array([11, 12, 13, 14, 15])

In [38]:
# py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [27]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [29]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [30]:
np_array_1 + np_array_2 # array addition is an element-wise operation

array([11, 22, 33, 44, 55])

In [31]:
np.concatenate([np_array_1, np_array_2])

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

## 2.5 Multiplying by a Number

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [34]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [36]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

In [39]:
# py_list**2                      # Won't work!  

## 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [41]:
py_list == 3     # Works, but what IS the question?

False

In [42]:
np_array == 3

array([False, False,  True, False, False])

In [43]:
np_array > 3  

array([False, False, False,  True,  True])

In [48]:
#py_list > 3      # Won't work! 
                 # TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [51]:
print(sum(py_list))    # sum() is a base Python function
print(max(py_list))    # max() is a base Python function
print(min(py_list))    # min() is a base Python function)

15
5
1


In [52]:
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())

15
5
1
3.0
1.4142135623730951


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes