<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [51]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [52]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = np_array

In [53]:
x[0]

'a1'

In [54]:
x[-1]

'j10'

In [55]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [56]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [57]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [58]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [59]:
x[:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [60]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [61]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [62]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [63]:
np_array[my_mask]  # shows only values > 3 (True)

array([ 4,  5,  6,  7,  8,  9, 10])

In [64]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [65]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [66]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [67]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [68]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [69]:
print(py_list_2d[3])
print(np_array_2d[3])

[4, 'D']
['4' 'D']


In [70]:
# gets the first element at index 3
print(py_list_2d[3][0])
print(np_array_2d[3, 0])

4
4


In [71]:
print(py_list_2d[:3])
print(np_array_2d[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [72]:
print(py_list_2d[:3][0])    # gives the first element of the sliced list
print(np_array_2d[:3, 0])   # gives the first index of each element in the list

[1, 'A']
['1' '2' '3']


In [73]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 1.4 Growing lists

In [74]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [75]:
%%time
x=[1]       # this method creates a new list each time 
x= x + [2]
x= x + [3]
x= x + [4]
x

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 8.11 µs


[1, 2, 3, 4]

In [76]:
%%time
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 7.87 µs


[1, 2, 3, 4]

In [77]:
%%time
x=[1]       # append modifies the original list
x.append(2)
x.append(3)
x.append(4)
x

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 6.91 µs


[1, 2, 3, 4]

In [78]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [79]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [80]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [81]:
a=(1, 2, 3)     # Define tuple

In [82]:
print(a[0])    # Access data

1


In [83]:
# The following will NOT work
## TypeError: 'tuple' object does not support item assignment
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
# y=x           # DON'T do this!
# z=x           # DON'T do this!

In [ ]:
x=[1, 2, 3]
y = x.copy()
z = x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes